# SERVER = 'http://34.229.80.49:9200'

SERVER = 'http://localhost:9200'

# Directories
# ROOT_DIRECTORY = '/data/data_loading/irdb_v3'
ROOT_DIRECTORY = '/data/data_loading/irdb_2018_06'
# BATCH_DATA_DIRECTORY = ROOT_DIRECTORY + "/batch_data"

INDEX = 'irdb_v4'
TYPE = 'grant'

ID_FIELD = 'appl_id'
ID_PREFIX = 'IRDB'

PROCESS_COUNT = 16

DATA_SOURCE_NAME = 'irdb'

DS_EXTENDED_RELATIONS = 'irdb_extended_relations'
DS_SPIRES_PUB_PROJECTS = 'spires_pub_projects'
DS_PATENT_RELATIONS = 'patent_relations'

DATA_SOURCE_APPLS_AT = 'appls_at'
DATA_SOURCE_APPLS_MV = 'appls_mv'

DATA_SOURCE_PVA_GRANT_PI_MV = 'pva_grant_pi_mv'

DATA_SOURCE_AWD_FUNDINGS = 'awd_fundings'
DATA_SOURCE_AWD_FUNDINGS_VW = 'awd_fundings_vw'
DATA_SOURCE_AWD_FUNDINGS_MV = 'awd_fundings_mv'
DATA_SOURCE_AWD_FUNDINGS_PUB = 'awd_fundings_pub'

DATA_SOURCE_ABSTRACTS = 'abstracts'
DATA_SOURCE_ABSTRACTS_ARCHIVED = 'abstracts_archived'

DATA_SOURCE_APPL_DC_BUDGETS_MV = 'appl_dc_budgets_mv'


DATA_SOURCE_FILES = {
    DATA_SOURCE_APPLS_AT: 'appls_vw.csv',
    DATA_SOURCE_APPLS_MV: 'appls_mv.csv',
    DATA_SOURCE_PVA_GRANT_PI_MV: 'pvp_grant_pi_mv.csv',
    DATA_SOURCE_AWD_FUNDINGS: 'awd_fundings.csv',
    DATA_SOURCE_AWD_FUNDINGS_MV: 'awd_fundings_mv.csv',
    DATA_SOURCE_AWD_FUNDINGS_PUB: 'awd_fundings_pub.csv',
    DATA_SOURCE_AWD_FUNDINGS_VW: 'awd_fundings_vw.csv',
    DATA_SOURCE_ABSTRACTS: 'abstracts_vw.csv',
    DATA_SOURCE_ABSTRACTS_ARCHIVED: 'archived_abstracts_vw.csv',
    DATA_SOURCE_APPL_DC_BUDGETS_MV: 'appl_dc_budgets_mv.csv'
}

DATA_SOURCE_PROCESSING_ORDER = [
    DATA_SOURCE_APPLS_AT,
    DATA_SOURCE_APPLS_MV,
    DATA_SOURCE_PVA_GRANT_PI_MV,
    DATA_SOURCE_AWD_FUNDINGS,
    DATA_SOURCE_AWD_FUNDINGS_MV,
    DATA_SOURCE_AWD_FUNDINGS_PUB,
    DATA_SOURCE_AWD_FUNDINGS_VW,
    DATA_SOURCE_ABSTRACTS,
    DATA_SOURCE_ABSTRACTS_ARCHIVED,
    DATA_SOURCE_APPL_DC_BUDGETS_MV
]

# pva_grant_pi_mv.json
ADD_DATA_FIELDS = {
    'PI_FIRST_NAME',
    'PI_LAST_NAME',
    'PI_MI_NAME',
    'PI_PROFILE_PERSON_ID',
    'EXTERNAL_ORG_ID',
    'ORG_NAME',
    'JOINT_FUNDED_APPL_CODE',
    'PRIORITY_SCORE_NUM',
    'ANIMAL_SUBJECTS_CODE',
    'GENDER_CLINICAL_STUDY_CODE',
    'HUMAN_SUBJECT_CODE',
}

# awd_fundings.json, awd_fundings_pub.json
AWD_FIELDS = {
    'AWARDED_DIRECT_COST_AMT',
    'AWARDED_INDIRECT_COST_AMT',
    'CAN',
    'DEOBLIGATION_AMT',
    'FY',
    'PERIOD_TYPE_CODE',
    'PHS_ORG_CODE',
    'PROG_CLASS_CODE',
    'TOTAL_AWARDED_AMT',
    'TOTAL_OBLGTD_AMT',
    'UNOBLGTD_BAL_AMT'
}

# appls_at.json, appls_mv.json
GRANTS_FIELDS = [
    'APPL_ID',
    'FY',
    'PROG_CLASS_CODE',
    'ACTIVITY_CODE',
    'ADMIN_PHS_ORG_CODE',
    'APPL_CLASS_CODE',
    'APPL_STATUS_CODE',
    'APPL_SUB_TYPE_CODE',
    'APPL_TYPE_CODE',
    'ARRA_FLAG',
    'COFUNDING_INDICATOR_CODE',
    'COMPETING_GRANT_CODE',
    'FUNDING_RECOMMENDED_CODE',
    'GRANT_NUM',
    'IC_SUBPROJECT_ID',
    'MAJOR_ACTIVITY_CODE',
    'MECHANISM_CODE',
    'PROJECT_NUM',
    'PROJECT_PERIOD_END_DATE',
    'PROJECT_PERIOD_START_DATE',
    'PROJECT_TITLE',
    'RFA_PA_NUMBER',
    'SERIAL_NUM',
    'SOURCE_CODE_DC',
    'SPECIAL_DISP_CODE',
    'SUBPROJECT_ID',
    'SUBPROJECT_TYPE_CODE',
    'TOTAL_COST_REQUESTED_AMT',
    'YEARS_RECOMMENDED_NUM',
    'ESI_APPL_ELIG_FLAG',
    'IRG_CODE',
    'IRG_FLEX_CODE',
    'IRG_PERCENTILE_NUM',
    'IRG_RECOM_CODE',
    'MODULAR_GRANT_FLAG',
    'MULTI_PI_INDICATOR_CODE',
    'NEW_INVESTIGATOR_CODE',
    'PROG_CLASS_CODE',
    'SUPPORT_YEAR'
]

CSV_HEADERS = {
    'APPL_DC_BUDGETS_MV.csv': 'APPL_ID,DC_ID,CREATOR_ID,CREATED_DATE,LAST_UPD_ID,LAST_UPD_DATE,ALLOCATED_AMT,FUNDING_PHS_ORG_CODE,CAN',
    'APPLS_AT.csv': 'SOURCE_CODE_DC,ABSTRACT_EXISTS_CODE,ACCESSION_NUM,ACTIVATION_DATE,ACTIVITY_CODE,ADHOC_IRG_CODE,ADHOC_IRG_FLEX_CODE,ADMIN_PHS_ORG_CODE,AGENCY_ROUTING_NUM,AIDS_RELATED_CODE,ANIMAL_SUBJECTS_CODE,ANIMAL_SUBJECT_ASSURANCE_NUM,ANIMAL_SUBJECT_IACUC_DATE,ANIMAL_SUBJECT_INDEFINITE_FLAG,APPLICANT_TYPE_CODE,APPLICANT_TYPE_TEXT,APPLIED_RESEARCH_PCT,APPL_CLASS_CODE,APPL_FORM_TYPE_CODE,APPL_ID,APPL_RECEIPT_DUE_DATE,APPL_RECEIVED_DATE,APPL_SHELL_FLAG,APPL_SOURCE_CODE,APPL_STATUS_CODE,APPL_STATUS_DATE,APPL_SUB_TYPE_CODE,APPL_SYSTEM_OWNERSHIP_CODE,APPL_TYPE_CODE,APPROVAL_LIST_NUM,AREA_OF_TRAINING_TEXT,ARRA_FLAG,ASSIGNMENT_SOURCE_CODE,AWD_CFDA_CODE,AWD_DOC_NUM,AWD_IDC_FILE_UPD_DATE,AWD_NOTICE_ISSUED_DATE,AWD_RELEASE_CNT,BASIC_RESEARCH_PCT,BUS_OFC_ADDR_SEQ_NUM,CHILD_CLINICAL_STUDY_CODE,CHIMP_SUBJECT_CODE,CITY_STATE_NAME,CLINICAL_TRIAL_CODE,COFUNDING_INDICATOR_CODE,COMMITMENT_DOC_NUM,COMPLEX_APPLICATION_FLAG,CONTRACT_DOC_NUM,CONTRACT_NUM,CONVERSION_CODE,COUNCIL_MEETING_DATE,COUNCIL_RECOM_CODE,CREATED_DATE,CREATOR_ID,CRISP_STATUS_CODE,CS_APPL_ELIG_FLAG,CURR_AWD_NOTICE_ISSUE_DATETIME,DEPT_CODE,DEPT_SEQ_NUM,DEVELOPMENTAL_RESEARCH_PCT,DIRECT_COST_REQUESTED_AMT,DISCLOSURE_PERMISSION_CODE,DIVISION_SEQ_NUM,DRG_CONTROL_CODE,DSF_CODE,DUAL_MEETING_DATE,DUAL_PRIORITY_CODE,DUAL_RECOM_CODE,DUNS_ID,EIN,ENGA_INDICATOR_CODE,ENVIRONMENT_IMPACT_FLAG,ESI_APPL_ELIG_FLAG,ESNAP_EXISTS_CODE,EXEMPT_FED_REGULATION_FLAG,EXPANDED_AUTHORITIES_CODE,EXPEDITED_REVIEW_CODE,EXTENSION_ELIGIBLE_CODE,EXTENSION_SUBMITTED_FLAG,EXTERNAL_ORG_ID,EXTERNAL_ORG_WIP_FLAG,FED_DEMO_PROJECT_CODE,FFATA_ELIGIBLE_CODE,FOREIGN_APPL_CODE,FORMER_NUM,FOT_CODE,FSR_ACCEPTED_CODE,FUNDING_RECOMMENDED_CODE,FY,GENDER_CLINICAL_STUDY_CODE,GRANT_IMAGE_EXISTS_CODE,GRANT_NUM,GROUP_CODE,GROUP_EXT_CODE,HIGH_RISK_IMPACT_RSRCH_CODE,HISTORIC_SITE_FLAG,HUMAN_SUBJECT_ASSURANCE_NUM,HUMAN_SUBJECT_CODE,HUMAN_SUBJECT_INDEFINITE_FLAG,HUMAN_SUBJECT_IRB_DATE,ICD_DISP_CODE,ICD_REVIEW_DATE,ICD_SPECIAL_CODE,ICD_SPECIAL_CODE_CMNT,IC_APPROVED_CODE,IC_APPROVER_ID,IC_SUBPROJECT_ID,INCLUSION_MONITORING_CODE,INDEXED_CODE,INDIRECT_COST_REQUESTED_AMT,INITIATIVE_TYPE_CODE,INIT_ENCUMBRANCE_DATE,INST_ADDR_SEQ_NUM,INTENT_TO_PAY_CODE,INTERIM_FUNDING_CODE,INVENTION_CODE,INVENTION_REPORTED_CODE,IRB_EXPEDITED_REVIEW_CODE,IRG_CODE,IRG_FLEX_CODE,IRG_MEETING_DATE,IRG_PERCENTILE_NUM,IRG_PERCENTILE_REF_CODE,IRG_RECOM_CODE,IRG_ROUND_CODE,KIND_OF_RECORD_CODE,LAST_AWD_NOTICE_ISSUE_DATETIME,LAST_UPD_DATE,LAST_UPD_ID,LATEST_ENCUMBRANCE_DATE,LEGACY_SOURCE_FILE,LEVEL_TYPE_CODE,LICENSURE_CODE,MAA_CLUSTER_ID,MAJOR_ACTIVITY_CODE,MAJOR_COMPONENT_CODE,MAJOR_COMPONENT_SEQ_NUM,MECHANISM_ASSIGN_DATETIME,MECHANISM_ASSIGN_ID,MECHANISM_CODE,MIDYEAR_TRANSFER_CODE,MINORITY_CLINICAL_STUDY_CODE,MODULAR_GRANT_FLAG,MOD_NUM,MONTHS_REQUESTED_NUM,MULTIYEAR_AWARD_FLAG,MULTI_PI_INDICATOR_CODE,NEW_INVESTIGATOR_CODE,NGA_LINE_ITEM_CODE,NOMINATING_COUNTRY_CODE,NOTICE_NUM,NOTICE_TYPE_CODE,NOTICE_YEAR,OBLGTN_CONTROL_NUM,ORG_CODE,ORG_COMPONENT_CODE,OTHER_COUNTRY_CODE,OUT_YEARS_NUM,PHASE_3_CLINICAL_TRIAL_CODE,PRECEPTOR_COUNTRY_CODE,PREVENTION_CODE,PRIORITY_CODE,PRIORITY_SCORE_NUM,PROG_CLASS_CODE,PROG_INCOME_TYPE_CODE,PROJECT_NUM,PROJECT_PERIOD_END_DATE,PROJECT_PERIOD_START_DATE,PROJECT_TITLE,RELEASE_NUM,RESEARCH_AREA_CODE,RFA_PA_NUMBER,SBIR_TOPIC_CODE,SCI_CLASS_CODE,SERIAL_NUM,SMALL_BUS_CODE,SNAP_INDICATOR_CODE,SORT_TERM_TEXT,SPECIAL_CONSIDER_CODE,SPECIAL_DISP_CODE,SPECIAL_SUPP_CODE,SPONSOR_NAME,SRA_DESIGNATOR_CODE,SRA_FLEX_CODE,SS_ADMIN_NOTE_FLAG,SS_ANIMAL_SUBJECT_COMMENT_CODE,SS_BIOHAZARD_FLAG,SS_BUDGETARY_OVERLAP_CODE,SS_BUDGET_COMMENTS_FLAG,SS_FOREIGN_FLAG,SS_REVISION_NOTE_CODE,STEM_CELLS_USED_CODE,STTR_INST_CITY_STATE,STTR_INST_NAME,STTR_RESEARCH_INST_AMT,STTR_SMALL_BUS_AMT,SUBMTD_ORG_ID,SUBMTD_PHS_ORG_CODE,SUBPROJECT_ID,SUBPROJECT_TYPE_CODE,SUFFIX_CODE,SUMMARY_STATEMENT_EXISTS_CODE,SUPPORT_YEAR,SUPP_TYPE_CODE,TASK_NUM,TERMINATION_CODE,TOTAL_COST_REQUESTED_AMT,TOTAL_COST_REQUESTED_YEAR1_AMT,TRACKING_EXCEPTION_CODE,TRANSFER_STATUS_CODE,TRIAGE_CODE,VERIFICATION_REPORT_CODE,WIP_ACTIVATION_DATE,WIP_COFUNDING_INDICATOR_CODE,WIP_EIN,WIP_LAST_UPD_DATETIME,WIP_PROJECT_PERIOD_END_DATE,WIP_PROJECT_PERIOD_START_DATE,WIP_SPECIAL_DISP_CODE,WIP_STATUS_CODE,WIP_TERMS_STATUS_CODE,WITHOUT_COUNCIL_REVIEW_CODE,YEARS_RECOMMENDED_NUM,COMPETING_GRANT_CODE',
    'APPLS_MV.csv': 'APPL_ID,APPL_TYPE_CODE,ACTIVITY_CODE,ADMIN_PHS_ORG_CODE,SERIAL_NUM,SUPPORT_YEAR,SUFFIX_CODE,SUBPROJECT_ID,APPL_CLASS_CODE,MOD_NUM,TASK_NUM,MAJOR_ACTIVITY_CODE,CREATOR_ID,CREATED_DATE,ACTIVATION_DATE,AIDS_RELATED_CODE,ANIMAL_SUBJECTS_CODE,ANIMAL_SUBJECT_ASSURANCE_NUM,ANIMAL_SUBJECT_IACUC_DATE,APPLIED_RESEARCH_PCT,APPL_RECEIVED_DATE,APPL_SHELL_FLAG,APPL_STATUS_CODE,APPL_STATUS_DATE,APPL_SUB_TYPE_CODE,APPL_SYSTEM_OWNERSHIP_CODE,APPROVAL_LIST_NUM,AREA_OF_TRAINING_TEXT,AWD_CFDA_CODE,AWD_DOC_NUM,AWD_IDC_FILE_UPD_DATE,AWD_NOTICE_ISSUED_DATE,AWD_RELEASE_CNT,BASIC_RESEARCH_PCT,BUS_OFC_ADDR_SEQ_NUM,CITY_STATE_NAME,CLINICAL_TRIAL_CODE,COFUNDING_INDICATOR_CODE,CONVERSION_CODE,COUNCIL_MEETING_DATE,COUNCIL_RECOM_CODE,CURR_AWD_NOTICE_ISSUE_DATETIME,DEPT_CODE,DEVELOPMENTAL_RESEARCH_PCT,DIRECT_COST_REQUESTED_AMT,DISCLOSURE_PERMISSION_CODE,DRG_CONTROL_CODE,DSF_CODE,EIN,ENGA_INDICATOR_CODE,EXPANDED_AUTHORITIES_CODE,EXPEDITED_REVIEW_CODE,EXTERNAL_ORG_ID,FED_DEMO_PROJECT_CODE,FOREIGN_APPL_CODE,FORMER_NUM,FUNDING_RECOMMENDED_CODE,FY,GENDER_CLINICAL_STUDY_CODE,GROUP_CODE,GROUP_EXT_CODE,HIGH_RISK_IMPACT_RSRCH_CODE,HUMAN_SUBJECT_ASSURANCE_NUM,HUMAN_SUBJECT_CODE,HUMAN_SUBJECT_IRB_DATE,ICD_DISP_CODE,ICD_REVIEW_DATE,ICD_SPECIAL_CODE,ICD_SPECIAL_CODE_CMNT,INDEXED_CODE,INDIRECT_COST_REQUESTED_AMT,INITIATIVE_TYPE_CODE,INIT_ENCUMBRANCE_DATE,INST_ADDR_SEQ_NUM,INVENTION_CODE,IRG_CODE,IRG_FLEX_CODE,IRG_MEETING_DATE,IRG_PERCENTILE_NUM,IRG_PERCENTILE_REF_CODE,IRG_RECOM_CODE,IRG_ROUND_CODE,KIND_OF_RECORD_CODE,LAST_AWD_NOTICE_ISSUE_DATETIME,LAST_UPD_DATE,LAST_UPD_ID,LATEST_ENCUMBRANCE_DATE,LEVEL_TYPE_CODE,LICENSURE_CODE,MAJOR_COMPONENT_CODE,MAJOR_COMPONENT_SEQ_NUM,MINORITY_CLINICAL_STUDY_CODE,MONTHS_REQUESTED_NUM,NOMINATING_COUNTRY_CODE,OBLGTN_CONTROL_NUM,ORG_CODE,ORG_COMPONENT_CODE,OUT_YEARS_NUM,PHASE_3_CLINICAL_TRIAL_CODE,PRECEPTOR_COUNTRY_CODE,PREVENTION_CODE,PRIORITY_CODE,PRIORITY_SCORE_NUM,PROG_CLASS_CODE,PROG_INCOME_TYPE_CODE,PROJECT_PERIOD_END_DATE,PROJECT_PERIOD_START_DATE,PROJECT_TITLE,RESEARCH_AREA_CODE,RFA_PA_NUMBER,SBIR_TOPIC_CODE,SCI_CLASS_CODE,SMALL_BUS_CODE,SNAP_INDICATOR_CODE,SPECIAL_CONSIDER_CODE,SPECIAL_DISP_CODE,SPECIAL_SUPP_CODE,SPONSOR_NAME,SRA_DESIGNATOR_CODE,SRA_FLEX_CODE,STTR_INST_CITY_STATE,STTR_INST_NAME,STTR_RESEARCH_INST_AMT,STTR_SMALL_BUS_AMT,SUBMTD_ORG_ID,SUBMTD_PHS_ORG_CODE,SUPP_TYPE_CODE,TERMINATION_CODE,TOTAL_COST_REQUESTED_AMT,TRACKING_EXCEPTION_CODE,TRIAGE_CODE,VERIFICATION_REPORT_CODE,WIP_STATUS_CODE,WITHOUT_COUNCIL_REVIEW_CODE,YEARS_RECOMMENDED_NUM,LEGACY_SOURCE_FILE,INTENT_TO_PAY_CODE,CRISP_STATUS_CODE,ADHOC_IRG_CODE,ADHOC_IRG_FLEX_CODE,DUAL_MEETING_DATE,DUAL_PRIORITY_CODE,DUAL_RECOM_CODE,IRB_EXPEDITED_REVIEW_CODE,OTHER_COUNTRY_CODE,NGA_LINE_ITEM_CODE,TRANSFER_STATUS_CODE,FSR_ACCEPTED_CODE,SORT_TERM_TEXT,TOTAL_COST_REQUESTED_YEAR1_AMT,NEW_INVESTIGATOR_CODE,INTERIM_FUNDING_CODE,CHILD_CLINICAL_STUDY_CODE,ACCESSION_NUM,IC_SUBPROJECT_ID,MECHANISM_CODE,MECHANISM_ASSIGN_ID,MECHANISM_ASSIGN_DATETIME,WIP_TERMS_STATUS_CODE,MODULAR_GRANT_FLAG,SS_BUDGET_COMMENTS_FLAG,SS_ADMIN_NOTE_FLAG,SS_BIOHAZARD_FLAG,SS_FOREIGN_FLAG,EXTERNAL_ORG_WIP_FLAG,SUBPROJECT_TYPE_CODE,IC_APPROVED_CODE,FOT_CODE,DUNS_ID,STEM_CELLS_USED_CODE,APPL_RECEIPT_DUE_DATE,SS_REVISION_NOTE_CODE,DEPT_SEQ_NUM,DIVISION_SEQ_NUM,MIDYEAR_TRANSFER_CODE,GRANT_NUM,IC_APPROVER_ID,INVENTION_REPORTED_CODE,EXTENSION_ELIGIBLE_CODE,SS_ANIMAL_SUBJECT_COMMENT_CODE,APPLICANT_TYPE_CODE,APPLICANT_TYPE_TEXT,SS_BUDGETARY_OVERLAP_CODE,APPL_FORM_TYPE_CODE,SUMMARY_STATEMENT_EXISTS_CODE,GRANT_IMAGE_EXISTS_CODE,ESNAP_EXISTS_CODE,ABSTRACT_EXISTS_CODE,MULTI_PI_INDICATOR_CODE,APPL_SOURCE_CODE,COMMITMENT_DOC_NUM,CONTRACT_DOC_NUM,CONTRACT_NUM,RELEASE_NUM,PROJECT_NUM,NOTICE_YEAR,CS_APPL_ELIG_FLAG,COMPETING_GRANT_CODE',    'AWD_FUNDINGS_MV.csv': 'APPL_ID,PERIOD_TYPE_CODE,APPL_PERIOD_NUM,CAN,FSR_SEQ_NUM,PROG_CLASS_CODE,PHS_ORG_CODE,CREATOR_ID,CREATED_DATE,LAST_UPD_ID,LAST_UPD_DATE,AWARDED_DIRECT_COST_AMT,AWARDED_INDIRECT_COST_AMT,AWD_TYPE_CODE,DEOBLIGATION_AMT,FY,FEE_AMT,JOINT_FUNDING_CR_AMT,TOTAL_AWARDED_AMT,UNOBLGTD_BAL_AMT,FRACTIONAL_CREDIT_PCT,LEGACY_SOURCE_FUNDING,TOTAL_OBLGTD_AMT',
    'AWD_FUNDINGS_MV.csv': 'APPL_ID,PERIOD_TYPE_CODE,APPL_PERIOD_NUM,CAN,FSR_SEQ_NUM,PROG_CLASS_CODE,PHS_ORG_CODE,CREATOR_ID,CREATED_DATE,LAST_UPD_ID,LAST_UPD_DATE,AWARDED_DIRECT_COST_AMT,AWARDED_INDIRECT_COST_AMT,AWD_TYPE_CODE,DEOBLIGATION_AMT,FY,FEE_AMT,JOINT_FUNDING_CR_AMT,TOTAL_AWARDED_AMT,UNOBLGTD_BAL_AMT,FRACTIONAL_CREDIT_PCT,LEGACY_SOURCE_FUNDING,TOTAL_OBLGTD_AMT',
    'AWD_FUNDINGS_PUB.csv': 'APPL_ID,PERIOD_TYPE_CODE,APPL_PERIOD_NUM,CAN,FSR_SEQ_NUM,PROG_CLASS_CODE,PHS_ORG_CODE,CREATOR_ID,CREATED_DATE,LAST_UPD_ID,LAST_UPD_DATE,AWARDED_DIRECT_COST_AMT,AWARDED_INDIRECT_COST_AMT,AWD_TYPE_CODE,DEOBLIGATION_AMT,FY,FEE_AMT,JOINT_FUNDING_CR_AMT,TOTAL_AWARDED_AMT,UNOBLGTD_BAL_AMT,FRACTIONAL_CREDIT_PCT,LEGACY_SOURCE_FUNDING,TOTAL_OBLGTD_AMT,SOURCE_CODE_DC,ADJUSTMENT_AMT',
    'PVP_GRANT_PI_MV.csv': 'SOURCE_CODE_DC,ACTIVITY_CODE,ADHOC_IRG_FLEX_CODE,ADMIN_PHS_ORG_CODE,AIDS_RELATED_CODE,ANIMAL_SUBJECTS_CODE,APPL_ID,APPL_RECEIVED_DATE,APPL_STATUS_CODE,APPL_STATUS_DATE,APPL_TYPE_CODE,AWD_DOC_NUM,CHILD_CLINICAL_STUDY_CODE,COUNCIL_MEETING_DATE,DEPT_CODE,DEPT_SEQ_NUM,DIVISION_SEQ_NUM,EIN,EXTERNAL_ORG_ID,FOREIGN_APPL_CODE,FORMER_NUM,FSR_ACCEPTED_CODE,FY,GENDER_CLINICAL_STUDY_CODE,GROUP_CODE,HUMAN_SUBJECT_CODE,INTENT_TO_PAY_CODE,INTERIM_FUNDING_CODE,IRG_CODE,IRG_FLEX_CODE,IRG_PERCENTILE_NUM,IRG_PERCENT_REF_CODE,IRG_RECOM_CODE,MAJOR_COMPONENT_CODE,MAJOR_COMPONENT_SEQ_NUM,MECHANISM_CODE,MINORITY_CLINICAL_STUDY_CODE,MODULAR_GRANT_FLAG,MULTI_PI_INDICATOR_CODE,NEW_INVESTIGATOR_CODE,PHASE_3_CLINICAL_TRIAL_CODE,PRIORITY_SCORE_NUM,PROG_CLASS_CODE,PROJECT_PERIOD_END_DATE,PROJECT_PERIOD_START_DATE,PROJECT_TITLE,RFA_PA_NUMBER,SERIAL_NUM,SMALL_BUS_CODE,SNAP_INDICATOR_CODE,SPECIAL_DISP_CODE,SRA_DESIGNATOR_CODE,SRA_FLEX_CODE,STEM_CELLS_USED_CODE,STTR_INST_CITY_STATE,STTR_INST_NAME,STTR_RESEARCH_INST_AMT,STTR_SMALL_BUS_AMT,SUFFIX_CODE,SUPPORT_YEAR,TRACKING_EXCEPTION_CODE,WIP_STATUS_CODE,CLINICAL_TRIAL_CODE,OUT_YEARS_NUM,ABSTRACT_EXISTS_CODE,SS_EXISTS_CODE,GRANT_IMAGE_EXISTS_CODE,FULL_GRANT_NUM,PERIOD_MONTHS,LAST_UPD_DATE,APPL_STATUS_GROUP_CODE,APPL_STATUS_GROUP_DESCRIP,INTERIM_FUNDING_DESCRIP,PHS_AGENCY_CODE,PARENT_PHS_ORG_CODE,ORG_NAME,INSTN_BUS_LINE_1_ADDR,INSTN_BUS_LINE_2_ADDR,INSTN_BUS_LINE_3_ADDR,INSTN_BUS_LINE_4_ADDR,INSTN_BUS_LINE_5_ADDR,INSTN_BUS_STATE_CODE,INSTN_BUS_ZIP_CODE,INSTN_BUS_CONGRSNL_DISTR_CODE,INSTN_BUS_CITY_NAME,INSTN_BUS_COUNTRY_SEQ_NUM,INSTN_BUS_COUNTRY_NAME,SS_RELEASE_DATE,SS_PROCESS_STAGE_CODE,SS_PROCESS_STAGE_DESCRIP,PROJECT_SUMMARY_ID,PI_FIRST_NAME,PI_LAST_NAME,PI_MI_NAME,PI_NAME_PREFIX,PI_NAME_SUFFIX,PI_PROFILE_PERSON_ID,PI_ROLE_PERSON_ID,PI_SSN,PI_TRANS_FIRST_NAME,PI_TRANS_LAST_NAME,PI_TRANS_MI_NAME,PI_WRK_LINE_1_ADDR,PI_WRK_LINE_2_ADDR,PI_WRK_LINE_3_ADDR,PI_WRK_LINE_4_ADDR,PI_WRK_LINE_5_ADDR,PI_EMAIL_ADDR,PI_WRK_CITY_NAME,PI_WRK_COUNTRY_SEQ_NUM,PI_WRK_PHONE_EXT_NUM,PI_WRK_PHONE_NUM,PI_WRK_STATE_CODE,PI_WRK_ZIP_CODE,PI_WRK_FAX_NUM,PI_WRK_COUNTRY_NAME,ACTIVATED_FELLOWSHIP_CODE,INSTN_PROFILE_STATE_CODE,GS_FIRST_NAME,GS_LAST_NAME,GS_MI_NAME,GS_PERSON_ID,GMO_FIRST_NAME,GMO_LAST_NAME,GMO_MI_NAME,GMO_PERSON_ID,SRA_FIRST_NAME,SRA_LAST_NAME,SRA_MI_NAME,SRA_PERSON_ID,EST_POSTDOC_COUNT,EST_POSTDOC_FTTP_COUNT,EST_PREDOC_COUNT,EST_PREDOC_FTTP_COUNT,EST_SHORT_TERM_TRAINEE_COUNT,EST_SHORT_TERM_FTTP_COUNT,JOINT_FUNDED_APPL_CODE,FUNDED_APPL_CODE,ACTIVE_GRANT_FLAG,APPL_PERIOD_START_DATE,APPL_PERIOD_END_DATE',
}
